version: '3.8'

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./mlt_backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./mlt_backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./mlt_webapp
    command: ng serve --host 0.0.0.0
    volumes:
      - ./mlt_webapp:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data: